#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>

struct sound_seg {
    uint32_t size;
    int16_t *data;
};

struct sound_seg* tr_init();
void tr_destroy(struct sound_seg* obj);
size_t tr_length(struct sound_seg* seg);
void tr_read(struct sound_seg* track, int16_t* dest, size_t pos, size_t len);
void tr_write(struct sound_seg* track, int16_t* src, size_t pos, size_t len);
void wav_save(const char* fname, int16_t* src, size_t len);


int main() {
    printf("==========================================\n");
    printf("         Sound Segment Utility Test         \n");
    printf("        this file is generated by AI        \n")
    printf("==========================================\n");

    // 1. init a seg sound object
    printf("1. Calling tr_init()... ");
    struct sound_seg* my_track = tr_init();
    if (my_track == NULL) {
        printf("FAILURE: tr_init failed.\n");
        return 1;
    }
    printf("SUCCESS (Track Initialized, Length: %zu).\n", tr_length(my_track));

    int16_t test_samples[] = {100, 200, 300, 400, 500, 600, 700, 800};
    size_t samples_len = 8;

    printf("2. Writing %zu samples to the track (0-7)...\n", samples_len);
    tr_write(my_track, test_samples, 0, samples_len);

    size_t length = tr_length(my_track);
    printf("3. Checking length: Actual %zu.\n", length);

    size_t read_start = 2; 
    size_t read_count = 4;
    int16_t *read_buffer = (int16_t*) malloc(read_count * sizeof(int16_t));

    printf("4. Reading %zu samples starting at position %zu...\n", read_count, read_start);
    tr_read(my_track, read_buffer, read_start, read_count);

    printf("   Read Samples: [");
    for (size_t i = 0; i < read_count; i++) {
        printf("%d%s", read_buffer[i], (i == read_count - 1) ? "" : ", ");
    }
    printf("] (Expected: 300, 400, 500, 600)\n"); 

    printf("5. Attempting to save data to 'output_test.wav'...\n");
    wav_save("output_test.wav", my_track->data, tr_length(my_track));
    printf("   File saved successfully.\n");

    free(read_buffer);
    printf("6. Calling tr_destroy()...\n");
    tr_destroy(my_track);
    printf("   Cleanup successful.\n");

    printf("==========================================\n");
    return 0;
}
